export const initialData = {
  metadata: {
    appName: 'Pro-Mekari Procurement Demo',
    version: '1.0.0',
    generatedAt: new Date().toISOString(),
  },
  departments: [
    {
      id: 'dept-ops',
      code: 'OPS',
      name: 'Operasional',
      parentId: null,
      description: 'Mengelola operasi harian dan gudang.',
    },
    {
      id: 'dept-it',
      code: 'IT',
      name: 'Teknologi Informasi',
      parentId: 'dept-ops',
      description: 'Mengelola infrastruktur teknologi dan proyek digital.',
    },
    {
      id: 'dept-mkt',
      code: 'MKT',
      name: 'Pemasaran',
      parentId: 'dept-ops',
      description: 'Mengelola kampanye pemasaran dan promosi.',
    },
    {
      id: 'dept-fin',
      code: 'FIN',
      name: 'Keuangan',
      parentId: null,
      description: 'Mengelola akuntansi dan pembayaran.',
    },
    {
      id: 'dept-exec',
      code: 'EXE',
      name: 'Direksi',
      parentId: null,
      description: 'Tim eksekutif dan pimpinan divisi.',
    },
  ],
  categories: [
    {
      id: 'cat-supplies',
      name: 'Perlengkapan Kantor',
      type: 'OPEX',
      description: 'Kebutuhan operasional rutin seperti alat tulis dan pantry.',
      parentId: null,
    },
    {
      id: 'cat-ads',
      name: 'Iklan & Kampanye',
      type: 'OPEX',
      description: 'Belanja digital marketing dan sponsorship.',
      parentId: null,
    },
    {
      id: 'cat-hardware',
      name: 'Perangkat Keras',
      type: 'CAPEX',
      description: 'Pembelian aset teknologi seperti laptop dan server.',
      parentId: null,
    },
    {
      id: 'cat-software',
      name: 'Perangkat Lunak',
      type: 'CAPEX',
      description: 'Lisensi dan langganan perangkat lunak.',
      parentId: null,
    },
    {
      id: 'cat-services',
      name: 'Jasa Profesional',
      type: 'OPEX',
      description: 'Konsultan, pelatihan, dan jasa pihak ketiga lainnya.',
      parentId: null,
    },
  ],
  vendors: [
    {
      id: 'ven-1',
      name: 'PT Sinar Teknologi',
      address: 'Jl. M.H. Thamrin No. 21, Jakarta',
      contactPerson: 'Rudi Santoso',
      phone: '+62 21 555 1122',
      email: 'sales@sinartech.id',
      rating: 4.6,
      categories: ['cat-hardware', 'cat-software'],
    },
    {
      id: 'ven-2',
      name: 'CV Media Kreatif',
      address: 'Jl. Dipati Ukur No. 10, Bandung',
      contactPerson: 'Maya Putri',
      phone: '+62 22 7345 8877',
      email: 'halo@mediakreatif.co.id',
      rating: 4.2,
      categories: ['cat-ads', 'cat-services'],
    },
    {
      id: 'ven-3',
      name: 'PT Arta Supplies',
      address: 'Jl. Gatot Subroto No. 88, Jakarta',
      contactPerson: 'Andi Wijaya',
      phone: '+62 21 7788 9900',
      email: 'hello@artasupplies.co.id',
      rating: 4.0,
      categories: ['cat-supplies'],
    },
  ],
  employees: [
    {
      id: 'emp-nadia',
      fullName: 'Nadia Rahma',
      email: 'nadia.rahma@protekari.id',
      departmentId: 'dept-it',
      jobTitle: 'IT Support Specialist',
      roles: ['Requester'],
      managerId: 'emp-raka',
      phone: '+62 812 9911 2233',
      status: 'active',
    },
    {
      id: 'emp-bima',
      fullName: 'Bima Aditya',
      email: 'bima.aditya@protekari.id',
      departmentId: 'dept-mkt',
      jobTitle: 'Digital Marketing Executive',
      roles: ['Requester'],
      managerId: 'emp-adi',
      phone: '+62 819 2233 7788',
      status: 'active',
    },
    {
      id: 'emp-raka',
      fullName: 'Raka Pratama',
      email: 'raka.pratama@protekari.id',
      departmentId: 'dept-it',
      jobTitle: 'IT Operations Manager',
      roles: ['Line Manager'],
      managerId: 'emp-dita',
      phone: '+62 811 2233 4455',
      status: 'active',
    },
    {
      id: 'emp-dita',
      fullName: 'Dita Lestari',
      email: 'dita.lestari@protekari.id',
      departmentId: 'dept-it',
      jobTitle: 'Head of IT',
      roles: ['Head of IT', 'Department Head'],
      managerId: 'emp-lisa',
      phone: '+62 812 3344 5566',
      status: 'active',
    },
    {
      id: 'emp-adi',
      fullName: 'Adi Wirawan',
      email: 'adi.wirawan@protekari.id',
      departmentId: 'dept-mkt',
      jobTitle: 'Marketing Manager',
      roles: ['Line Manager'],
      managerId: 'emp-sarah',
      phone: '+62 812 7788 9900',
      status: 'active',
    },
    {
      id: 'emp-sarah',
      fullName: 'Sarah Mahendra',
      email: 'sarah.mahendra@protekari.id',
      departmentId: 'dept-mkt',
      jobTitle: 'Head of Marketing',
      roles: ['Head of Marketing', 'Department Head'],
      managerId: 'emp-lisa',
      phone: '+62 811 9900 1122',
      status: 'active',
    },
    {
      id: 'emp-farah',
      fullName: 'Farah Wibisono',
      email: 'farah.wibisono@protekari.id',
      departmentId: 'dept-ops',
      jobTitle: 'Procurement Lead',
      roles: ['Procurement Lead', 'Line Manager'],
      managerId: 'emp-lisa',
      phone: '+62 813 4455 6677',
      status: 'active',
    },
    {
      id: 'emp-yuni',
      fullName: 'Yuni Laksmi',
      email: 'yuni.laksmi@protekari.id',
      departmentId: 'dept-ops',
      jobTitle: 'Warehouse Supervisor',
      roles: ['Warehouse Lead'],
      managerId: 'emp-farah',
      phone: '+62 812 5566 7788',
      status: 'active',
    },
    {
      id: 'emp-roni',
      fullName: 'Roni Hartono',
      email: 'roni.hartono@protekari.id',
      departmentId: 'dept-fin',
      jobTitle: 'AP Specialist',
      roles: ['Finance AP'],
      managerId: 'emp-rudi',
      phone: '+62 813 7788 9911',
      status: 'active',
    },
    {
      id: 'emp-lisa',
      fullName: 'Lisa Wijaya',
      email: 'lisa.wijaya@protekari.id',
      departmentId: 'dept-exec',
      jobTitle: 'Director of Operations',
      roles: ['Division Director'],
      managerId: 'emp-rudi',
      phone: '+62 811 5566 7788',
      status: 'active',
    },
    {
      id: 'emp-rudi',
      fullName: 'Rudi Nugroho',
      email: 'rudi.nugroho@protekari.id',
      departmentId: 'dept-fin',
      jobTitle: 'Chief Financial Officer',
      roles: ['CFO'],
      managerId: null,
      phone: '+62 811 3344 5566',
      status: 'active',
    },
  ],
  budgets: [
    {
      id: 'bud-it-hw-2024',
      name: 'Anggaran Hardware IT 2024',
      departmentId: 'dept-it',
      categoryId: 'cat-hardware',
      allocation: 750000000,
      committed: 0,
      spent: 0,
      startDate: '2024-01-01',
      endDate: '2024-12-31',
      parentId: null,
      description: 'Pengadaan laptop, server, dan perangkat jaringan prioritas.',
    },
    {
      id: 'bud-it-sw-2024',
      name: 'Anggaran Software IT 2024',
      departmentId: 'dept-it',
      categoryId: 'cat-software',
      allocation: 320000000,
      committed: 0,
      spent: 0,
      startDate: '2024-01-01',
      endDate: '2024-12-31',
      parentId: null,
      description: 'Lisensi perangkat lunak enterprise dan SaaS.',
    },
    {
      id: 'bud-mkt-ads-q1',
      name: 'Anggaran Iklan Pemasaran Q1 2024',
      departmentId: 'dept-mkt',
      categoryId: 'cat-ads',
      allocation: 150000000,
      committed: 0,
      spent: 0,
      startDate: '2024-01-01',
      endDate: '2024-03-31',
      parentId: null,
      description: 'Kampanye digital dan sponsorship kuartal pertama.',
    },
    {
      id: 'bud-ops-supplies-2024',
      name: 'Anggaran Perlengkapan Operasional 2024',
      departmentId: 'dept-ops',
      categoryId: 'cat-supplies',
      allocation: 90000000,
      committed: 0,
      spent: 0,
      startDate: '2024-01-01',
      endDate: '2024-12-31',
      parentId: null,
      description: 'Kebutuhan alat tulis kantor dan logistik gudang.',
    },
    {
      id: 'bud-services-2024',
      name: 'Anggaran Jasa Profesional 2024',
      departmentId: 'dept-ops',
      categoryId: 'cat-services',
      allocation: 120000000,
      committed: 0,
      spent: 0,
      startDate: '2024-01-01',
      endDate: '2024-12-31',
      parentId: null,
      description: 'Pelatihan dan jasa konsultan lintas departemen.',
    },
  ],
  approvalMatrix: [
    {
      id: 'rule-1',
      name: 'Pembelian Supplies Rendah',
      departments: ['ALL'],
      categories: ['cat-supplies'],
      minAmount: 0,
      maxAmount: 5000000,
      levels: [
        {
          type: 'sequential',
          roles: ['Line Manager'],
        },
      ],
    },
    {
      id: 'rule-2',
      name: 'Iklan Pemasaran Menengah',
      departments: ['dept-mkt'],
      categories: ['cat-ads'],
      minAmount: 5000001,
      maxAmount: 50000000,
      levels: [
        {
          type: 'sequential',
          roles: ['Line Manager'],
        },
        {
          type: 'sequential',
          roles: ['Head of Marketing'],
        },
      ],
    },
    {
      id: 'rule-3',
      name: 'Investasi Hardware IT',
      departments: ['dept-it'],
      categories: ['cat-hardware'],
      minAmount: 0,
      maxAmount: null,
      levels: [
        {
          type: 'sequential',
          roles: ['Line Manager'],
        },
        {
          type: 'sequential',
          roles: ['Head of IT'],
        },
        {
          type: 'sequential',
          roles: ['CFO'],
        },
      ],
    },
    {
      id: 'rule-4',
      name: 'Belanja Besar Semua Departemen',
      departments: ['ALL'],
      categories: ['ALL'],
      minAmount: 50000001,
      maxAmount: 250000000,
      levels: [
        {
          type: 'sequential',
          roles: ['Line Manager'],
        },
        {
          type: 'sequential',
          roles: ['Department Head'],
        },
        {
          type: 'sequential',
          roles: ['Division Director'],
        },
      ],
    },
    {
      id: 'rule-5',
      name: 'Belanja Strategis Sangat Besar',
      departments: ['ALL'],
      categories: ['ALL'],
      minAmount: 250000001,
      maxAmount: null,
      levels: [
        {
          type: 'sequential',
          roles: ['Line Manager'],
        },
        {
          type: 'sequential',
          roles: ['Department Head'],
        },
        {
          type: 'parallel',
          roles: ['Division Director', 'CFO'],
        },
      ],
    },
  ],
  requisitions: [],
  purchaseOrders: [],
  goodsReceipts: [],
  invoices: [],
  counters: {
    PR: 1,
    PO: 1,
    GR: 1,
    INV: 1,
  },
};

export const currencyFormatter = new Intl.NumberFormat('id-ID', {
  style: 'currency',
  currency: 'IDR',
  minimumFractionDigits: 0,
});

export function cloneInitialData() {
  return JSON.parse(JSON.stringify(initialData));
}
